version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - static-content:/app/app/static
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-content:
